# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

### Storm Apps default configuration values
### Specific configuration values can be overridden by config.yaml

##############################################################################
### global.* configs are general configurations
##############################################################################


##############################################################################
### sentistorm.* configs are for the SentiStorm application
##############################################################################

# c3.8xlarge

sentistorm.workers.num: 1
#sentistorm.workers.childopts: "-Xmx4g"
sentistorm.workers.childopts: "-Xmx512m"

# supervisor childopts are useless - use storm.yaml instead
#sentistorm.supervisor.childopts: "-Xmx4g"
sentistorm.supervisor.childopts: "-Xmx512m"

sentistorm.spout.parallelism: 1
sentistorm.spout.max.pending: 150
sentistorm.spout.startup.sleep.ms: 20000 # 20 sec

sentistorm.bolt.tokenizer.parallelism: 1
sentistorm.bolt.tokenizer.logging: false

sentistorm.bolt.preprocessor.parallelism: 1
sentistorm.bolt.preprocessor.logging: false

sentistorm.bolt.postagger.parallelism: 5
sentistorm.bolt.postagger.logging: false

sentistorm.bolt.featuregeneration.parallelism: 2
sentistorm.bolt.featuregeneration.logging: false

sentistorm.bolt.svm.parallelism: 3
sentistorm.bolt.svm.logging: true
